### ISSUE TITLE
Iptables

### ISSUE THREAD

**Issue by GobiasSomeCoffeeCo** [00JCIV00/zing#1]
I hear you're having trouble with your packets getting marked invalid by iptables. Have you thought about rewriting it in rust? Not sure, but I'm guessing it'll fix the issue.

**Comment by 00JCIV00** [comment]
Feel free to submit a PR for that.

**Comment by GobiasSomeCoffeeCo** [comment]
You're quick to respond. You e earned a star!

**Comment by GobiasSomeCoffeeCo** [comment]
Also, please consider leaving the issue open...
